[phases.setup]
nixPkgs = ["nodejs_20", "python312", "python312Packages.pip"]

[phases.install]
cmds = ["cd frontend && npm i && cd ..", "pip install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = ["cd frontend && npm run build && cd ..", "python manage.py collectstatic --noinput"]
