[phases.setup]
nixPkgs = ["nodejs_20", "python312", "python312Packages.pip"]

[phases.install]
cmds = ["npm i", "pip install -r requirements.txt"]

[phases.build]
cmds = ["npm run build", "python manage.py collectstatic --noinput"]
