# Generated by Django 4.2.11 on 2026-04-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.PositiveIntegerField()),
                ('bricks', models.PositiveIntegerField()),
                ('cement', models.DecimalField(decimal_places=1, max_digits=10)),
                ('sand', models.DecimalField(decimal_places=1, max_digits=10)),
                ('source', models.CharField(choices=[('web', 'Web'), ('bot', 'Bot')], default='web', max_length=10)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
