# Generated by Django 4.2.11 on 2026-05-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_calc', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationproject',
            name='floors',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='calculationproject',
            name='foundation_type',
            field=models.CharField(choices=[('lenta', 'Lentali'), ('monolit', 'Monolit'), ('plita', 'Plita')], default='lenta', max_length=20),
        ),
        migrations.AddField(
            model_name='calculationproject',
            name='has_finishing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calculationproject',
            name='has_heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calculationproject',
            name='rebar',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calculationproject',
            name='roofing_type',
            field=models.CharField(choices=[('metal', 'Metal'), ('tile', 'Tile')], default='metal', max_length=20),
        ),
        migrations.AddField(
            model_name='calculationproject',
            name='wall_material',
            field=models.CharField(choices=[('brick', "Pishgan g'isht"), ('gazobeton', 'Gazobeton'), ('gipsokarton', 'Gipsokarton')], default='brick', max_length=20),
        ),
        migrations.AddField(
            model_name='calculationproject',
            name='wall_thickness',
            field=models.DecimalField(decimal_places=1, default=1.5, max_digits=3),
        ),
    ]
