# Generated by Codex on 2026-05-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house_calc', '0006_calculationproject_floors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationproject',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='calculation_projects',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
