# Generated by Codex on 2026-05-22
#
# NOTE: This migration is now a no-op on purpose. The ProjectFavorite model it
# created was already created by 0006_calculationproject_owner_and_more, so
# applying this on a fresh database raised `duplicate table name:
# projectfavorite`. The model is fully deleted again by
# 0010_remove_calculationproject_floors_and_more, so the net effect of the
# whole chain is zero. The entry is kept so the recorded migration history of
# existing databases stays consistent.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_calc', '0007_calculationproject_owner'),
    ]

    operations = [
    ]
