# Generated by Django 6.0.5 on 2026-06-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_calc', '0006_calculationproject_owner_and_more'),
        ('house_calc', '0008_projectfavorite'),
    ]

    operations = [
    ]
