# Generated by Django 4.2.11 on 2026-06-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_calc', '0009_merge_20260617_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationproject',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='calculationproject',
            name='foundation_type',
        ),
        migrations.RemoveField(
            model_name='calculationproject',
            name='has_finishing',
        ),
        migrations.RemoveField(
            model_name='calculationproject',
            name='has_heating',
        ),
        migrations.RemoveField(
            model_name='calculationproject',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='calculationproject',
            name='rebar',
        ),
        migrations.RemoveField(
            model_name='calculationproject',
            name='roofing_type',
        ),
        migrations.RemoveField(
            model_name='calculationproject',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='calculationproject',
            name='wall_material',
        ),
        migrations.RemoveField(
            model_name='calculationproject',
            name='wall_thickness',
        ),
        migrations.DeleteModel(
            name='ProjectFavorite',
        ),
    ]
