# Generated by Django 4.2.11 on 2026-08-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_calc', '0011_apiclient_productorder_storeowner_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationproject',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
