# Generated by Django 4.2.11 on 2026-08-07 19:23

from django.db import migrations, models


def backfill_features(apps, schema_editor):
    CalculationProject = apps.get_model('house_calc', 'CalculationProject')
    for project in CalculationProject.objects.all():
        features = []
        if project.has_pool:
            features.append('pool')
        if project.has_garage:
            features.append('garage')
        if project.has_terrace:
            features.append('terrace')
        # Larger, multi-room villas default to a modern glass facade + garden
        # so the richer material list shows up in demo data too.
        if project.area >= 300 and project.rooms >= 8:
            if 'modern_facade' not in features:
                features.append('modern_facade')
            if 'garden' not in features:
                features.append('garden')
        project.features = features
        project.save(update_fields=['features'])


class Migration(migrations.Migration):

    dependencies = [
        ('house_calc', '0012_calculationproject_images_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationproject',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_features, migrations.RunPython.noop),
    ]
