# Generated by Django 4.2.11 on 2026-08-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_calc', '0013_calculationproject_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_source',
            field=models.CharField(blank=True, default='seed', max_length=20),
        ),
    ]
