# Generated by Django 4.2.11 on 2026-08-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_calc', '0014_product_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationproject',
            name='technical_drawings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
